apiVersion: apps/v1
kind: Deployment
metadata:
  name: w-bot-deployment
  namespace: boytsova-na
  labels:
    app: w-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot
    spec:
      containers:
        - name: boot
          image: nataboytsova/boot:bot
          ports:
            - containerPort: 7000
