apiVersion: apps/v1
kind: Deployment
metadata:
  name: w-bot-deployment
  namespace: boytsova-na
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: nataboytsova/bot:latest
          ports:
            - containerPort: 7000
